### ISSUE TITLE
Update to Angular 12

### ISSUE THREAD

**Issue by MiroslavKral** [angular-extensions/model#25]
## Describe the feature you'd like:
Hello Tomas, do you plan to update this library to Angular 12?

## I would be willing to submit a PR to add this feature:
I could prepare PR for Angular 11 and 12. Would you accept this?

**Comment by tomastrajan** [comment]
@MiroslavKral would be very appreciated!

**Comment by MiroslavKral** [comment]
@tomastrajan there is PR for Angular 11: https://github.com/angular-extensions/model/pull/27

I will also prepare for Angular 12.

**Comment by tomastrajan** [comment]
@MiroslavKral thanks! Just release as 11.0.0 and looking forward to the next PR 👍

**Comment by MiroslavKral** [comment]
@tomastrajan and finaly for Angular 12 :-) https://github.com/angular-extensions/model/pull/28
