### ISSUE TITLE
receiving project_1.getProject is not a function when trying to generate model service

### ISSUE THREAD

**Issue by tomschreck** [angular-extensions/model#4]
## Minimal reproduction of the bug with instructions:
I installed the library using:

`ng add @angular-extensions/model`

then i attempted to create a model service:

`ng g @angular-extensions/model:model examples/todo --items`

I received this error:

project_1.getProject is not a function

## Expected behavior:

I expected the model service to be generated.  I'm following the examples provided in the documentation exactly.

## Other information:

I thought perhaps the issue stemmed from using Angular 6.x since @angular-extensions/model is version 7.x.  There's no information in documentation about which version of Angular is supported.  So, I went about upgrading to version 7.x for Angular and all of it's associated libraries.  After getting everything upgraded, I tried the exact same snippets from the documentation and I am receiving the exact same error.

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[ X] No

**Comment by tomastrajan** [comment]
Hi @tomschreck !

I guess this is caused by different version of the @angular/cli package, I am just performin a new release 7.0.1 which speciefies `@angular/cli: ^7.0.0` as a peerDependency. THis will cause warning during npm install if not present. Please give it a try!

**Comment by Sothecom** [comment]
So it's nearly 2 years on and I'm struggling with this same exact error - and I haven't even tried anything special. I get it trying to create my first component.
Anyone have any solution?

**Comment by tomastrajan** [comment]
Just release model @10.0.0 which was tested  with Angular 10 / CLI 10 including schematics should work now!
