### ISSUE TITLE
Version 7.1.0 is not working

### ISSUE THREAD

**Issue by vchmovzh-zz** [angular-extensions/model#6]
## Minimal reproduction of the bug with instructions:
1. npm i -S @angular-extensions/model
2. Create sample service, import Model, ModelFactory from @angular-extensions/model

## Expected behavior:
You can create a service and use it

## Other information:
There are errors during ng serve, in fact if you go to node_modules it pulls non-compiled repo.

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[ x] No

## Workaround
Currently 7.0.1 can be installed using
npm  i -S @angular-extensions/model@7.0.1

**Comment by tomastrajan** [comment]
uff sorry about that !

**Comment by tomastrajan** [comment]
Will have a look asap!

**Comment by tomastrajan** [comment]
@vchmovzh Ok the `7.1.1` is out! This was caused by the failed release (bad connection in a train tunnel) and then subsequent incorrect partial release. Now it should all be alright!

**Comment by vchmovzh-zz** [comment]
@tomastrajan well, that was fast! :) Like it! 👍

**Comment by tomastrajan** [comment]
@vchmovzh enjoy! :)
